name: Sync Upptime Status

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch Upptime README
      run: |
        curl -s https://raw.githubusercontent.com/fr0st-iwnl/status.fr0st.xyz/HEAD/README.md > upptime_readme.md

        # extract the section containing voux.fr0st.xyz
        awk '/voux\.fr0st\.xyz/{flag=1} /<\/details>/{if(flag){print; exit}} flag' upptime_readme.md > extracted_status.md

    - name: Inject into README
      run: |
        awk '
          /<!-- STATUS-START -->/ {
            print
            while (getline < "extracted_status.md") print
            p=1
            next
          }
          /<!-- STATUS-END -->/ {p=0}
          !p
        ' README.md > README.new

        mv README.new README.md

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update status table"
